-- Add employment status and details fields for both applicants
ALTER TABLE public.application_form_data 
ADD COLUMN IF NOT EXISTS app1_employment_status text DEFAULT 'employed',
ADD COLUMN IF NOT EXISTS app1_occupation text,
ADD COLUMN IF NOT EXISTS app1_employer_name text,
ADD COLUMN IF NOT EXISTS app1_employer_address text,
ADD COLUMN IF NOT EXISTS app1_employer_phone text,
ADD COLUMN IF NOT EXISTS app1_nature_of_business text,
ADD COLUMN IF NOT EXISTS app1_employment_type text DEFAULT 'permanent',
ADD COLUMN IF NOT EXISTS app1_years_with_employer integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_months_with_employer integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_net_monthly_income numeric DEFAULT 0,

-- Self-employed details for Applicant 1
ADD COLUMN IF NOT EXISTS app1_se_company_name text,
ADD COLUMN IF NOT EXISTS app1_se_company_address text,
ADD COLUMN IF NOT EXISTS app1_se_nature_of_business text,
ADD COLUMN IF NOT EXISTS app1_se_years_established integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_se_average_profit numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_se_shareholding_percent numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_se_accountant_name text,
ADD COLUMN IF NOT EXISTS app1_se_accountant_firm text,
ADD COLUMN IF NOT EXISTS app1_se_accountant_address text,
ADD COLUMN IF NOT EXISTS app1_se_accountant_phone text,
ADD COLUMN IF NOT EXISTS app1_se_audited_accounts boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app1_se_tax_affairs_uptodate boolean DEFAULT true,

-- Employment details for Applicant 2
ADD COLUMN IF NOT EXISTS app2_employment_status text DEFAULT 'employed',
ADD COLUMN IF NOT EXISTS app2_occupation text,
ADD COLUMN IF NOT EXISTS app2_employer_name text,
ADD COLUMN IF NOT EXISTS app2_employer_address text,
ADD COLUMN IF NOT EXISTS app2_employer_phone text,
ADD COLUMN IF NOT EXISTS app2_nature_of_business text,
ADD COLUMN IF NOT EXISTS app2_employment_type text DEFAULT 'permanent',
ADD COLUMN IF NOT EXISTS app2_years_with_employer integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_months_with_employer integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_net_monthly_income numeric DEFAULT 0,

-- Self-employed details for Applicant 2
ADD COLUMN IF NOT EXISTS app2_se_company_name text,
ADD COLUMN IF NOT EXISTS app2_se_company_address text,
ADD COLUMN IF NOT EXISTS app2_se_nature_of_business text,
ADD COLUMN IF NOT EXISTS app2_se_years_established integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_se_average_profit numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_se_shareholding_percent numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_se_accountant_name text,
ADD COLUMN IF NOT EXISTS app2_se_accountant_firm text,
ADD COLUMN IF NOT EXISTS app2_se_accountant_address text,
ADD COLUMN IF NOT EXISTS app2_se_accountant_phone text,
ADD COLUMN IF NOT EXISTS app2_se_audited_accounts boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app2_se_tax_affairs_uptodate boolean DEFAULT true,

-- Bank details
ADD COLUMN IF NOT EXISTS bank_name text,
ADD COLUMN IF NOT EXISTS bank_address text,
ADD COLUMN IF NOT EXISTS bank_account_type text,
ADD COLUMN IF NOT EXISTS bank_account_number text,
ADD COLUMN IF NOT EXISTS bank_sort_code text,
ADD COLUMN IF NOT EXISTS bank_years_held integer DEFAULT 0,

-- Solicitor details
ADD COLUMN IF NOT EXISTS solicitor_name text,
ADD COLUMN IF NOT EXISTS solicitor_address text,
ADD COLUMN IF NOT EXISTS solicitor_phone text,
ADD COLUMN IF NOT EXISTS solicitor_email text,

-- Additional mortgage details per BI form
ADD COLUMN IF NOT EXISTS mortgage_purpose text,
ADD COLUMN IF NOT EXISTS rate_type text DEFAULT 'fixed',
ADD COLUMN IF NOT EXISTS fixed_rate_years integer,
ADD COLUMN IF NOT EXISTS repayment_method text DEFAULT 'repayment',
ADD COLUMN IF NOT EXISTS max_approval_required boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS joint_title boolean DEFAULT true,

-- Additional address fields
ADD COLUMN IF NOT EXISTS app1_address_line1 text,
ADD COLUMN IF NOT EXISTS app1_address_line2 text,
ADD COLUMN IF NOT EXISTS app1_address_line3 text,
ADD COLUMN IF NOT EXISTS app1_county text,
ADD COLUMN IF NOT EXISTS app1_country text DEFAULT 'Ireland',
ADD COLUMN IF NOT EXISTS app1_residence_status text DEFAULT 'owner',
ADD COLUMN IF NOT EXISTS app1_rent_amount numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_correspondence_same boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS app1_correspondence_address text,
ADD COLUMN IF NOT EXISTS app1_previous_address text,
ADD COLUMN IF NOT EXISTS app1_previous_years integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app1_home_phone text,
ADD COLUMN IF NOT EXISTS app1_work_phone text,

ADD COLUMN IF NOT EXISTS app2_address_line1 text,
ADD COLUMN IF NOT EXISTS app2_address_line2 text,
ADD COLUMN IF NOT EXISTS app2_address_line3 text,
ADD COLUMN IF NOT EXISTS app2_county text,
ADD COLUMN IF NOT EXISTS app2_country text DEFAULT 'Ireland',
ADD COLUMN IF NOT EXISTS app2_residence_status text DEFAULT 'owner',
ADD COLUMN IF NOT EXISTS app2_rent_amount numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_correspondence_same boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS app2_correspondence_address text,
ADD COLUMN IF NOT EXISTS app2_previous_address text,
ADD COLUMN IF NOT EXISTS app2_previous_years integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS app2_home_phone text,
ADD COLUMN IF NOT EXISTS app2_work_phone text,

-- Credit history questions per BI form
ADD COLUMN IF NOT EXISTS app1_refused_mortgage boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app1_refused_mortgage_details text,
ADD COLUMN IF NOT EXISTS app1_court_order boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app1_court_order_details text,
ADD COLUMN IF NOT EXISTS app1_bankruptcy boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app1_bankruptcy_details text,
ADD COLUMN IF NOT EXISTS app1_mortgage_arrears_24m boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app1_mortgage_arrears_details text,

ADD COLUMN IF NOT EXISTS app2_refused_mortgage boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app2_refused_mortgage_details text,
ADD COLUMN IF NOT EXISTS app2_court_order boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app2_court_order_details text,
ADD COLUMN IF NOT EXISTS app2_bankruptcy boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app2_bankruptcy_details text,
ADD COLUMN IF NOT EXISTS app2_mortgage_arrears_24m boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS app2_mortgage_arrears_details text,

-- Property details per BI form
ADD COLUMN IF NOT EXISTS property_address_line1 text,
ADD COLUMN IF NOT EXISTS property_address_line2 text,
ADD COLUMN IF NOT EXISTS property_address_line3 text,
ADD COLUMN IF NOT EXISTS property_county text,
ADD COLUMN IF NOT EXISTS property_country text DEFAULT 'Ireland',
ADD COLUMN IF NOT EXISTS property_estimated_value numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS property_num_living_rooms integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS property_num_dining_rooms integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS property_num_bedrooms integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS property_num_bathrooms integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS property_num_kitchens integer DEFAULT 0,
ADD COLUMN IF NOT EXISTS property_tenure text DEFAULT 'freehold',
ADD COLUMN IF NOT EXISTS property_lease_years integer,
ADD COLUMN IF NOT EXISTS property_vacant_possession boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS property_construction_type text,

-- Declarations
ADD COLUMN IF NOT EXISTS declarations_signed boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS consent_consumer_credit boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS consent_data_protection boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS consent_contact_home boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS consent_contact_work boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS consent_leave_message boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS consent_contact_employer boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS consent_email boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS consent_sms boolean DEFAULT true;