// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urdyzlulkpgffzrwefwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZHl6bHVsa3BnZmZ6cndlZndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NDE0MjQsImV4cCI6MjA3ODAxNzQyNH0.HMp_O3JfQ5wKdfBQg8aqUwSWzur12_iIWOUGmNLNBy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});